### ISSUE TITLE
Support For Pelican

### ISSUE THREAD

**Issue by ItsmagmaMan09** [TubYoub/VelocityPteroPower#2]
It would be cool if we had support for Pelican panel too, I tested it and it couldn't start the servers. [pelican.dev](https://pelican.dev)

**Comment by TubYoub** [comment]
Hi, thanks for the suggestion.
I am currently working on another [Plugin](https://github.com/BT-Pluginz/GravePlugin) but when I'm finished with it i will look into the integration of [pelican.dev](https://pelican.dev). I couldn't find a Documentation for the API yet, if you have a Link for that it would help allot.
I will also have to setup a local Pelican distance so it will all take a few days or more.

**Comment by ItsmagmaMan09** [comment]
I asked the developers and they said that the documentation was found within the panel when you go to https://yourpaneliphere/docs/api

**Comment by TubYoub** [comment]
Sorry took so long but the Plugin should now support the Pelican. let me know if it has issues
You can download the plugin right here on Github or on Modrinth
